[package]
name = "flashroute_rs"
version = "0.1.0"
authors = ["Bugen Zhao <i@bugenzhao.com>", "Zhengdong Wang <lnwzd2009@sjtu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
